spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:
  expiration: